### ISSUE TITLE
Mismatch between Glasser Parcels and Cole-Anticevic Communities

### ISSUE THREAD

**Issue by amsinha9** [ColeLab/ColeAnticevicNetPartition#10]
There seems to be a mismatch between the order of the Glasser parcels (all left hemisphere regions first - i.e. the first 180 correspond to left regions, the last 180 correspond to right regions) and those in cortex_community_order.mat and cortex_parcel_network_assignments.mat.
[GlasserToColeAnticevicMapping.txt](https://github.com/ColeLab/ColeAnticevicNetPartition/files/4806425/GlasserToColeAnticevicMapping.txt)

See attached GlasserToColeAnticevicMapping.txt file, in which the Glasser parcels have been reordered in ascending order. For example, parcel #1 and #181 should correspond to the left primary visual cortex and right primary visual cortex, respectively, however, in the mat files you have provided, it shows that parcel #1 belongs to the Cole-Anticevic Network #1, while parcel #181 belongs to Cole-Anticevic Network #6. I believe the right and left hemisphere parcels should belong to the same network, correct?
[Glasser2016-supplement-Neuroanatomical_Supplementary_Results.pdf](https://github.com/ColeLab/ColeAnticevicNetPartition/files/4806444/Glasser2016-supplement-Neuroanatomical_Supplementary_Results.pdf)

Starting on page 81 of the Neuroanatomical Supplementary Results from Glasser et. al. 2016, the order of the Glasser parcels are listed in the table. This is the order I am going off of when I refer to a mismatch between the mat files on Github and the Glasser parcels.

Could you provide some clarification on this?

**Comment by jielisaji** [comment]
Hi Anita, I think this discrepancy may have occurred when I switched the order of L and R hemisphere parcels during a version update to conform with the Glasser parcellation, but overlooked the Matlab file. I will look into it tonight. Thank you for bringing this to my attention!

**Comment by amsinha9** [comment]
Thanks for the response! Yes, please let me know what the correct mapping from Glasser parcellation to Cole-Anticevic is, as I am using it for some current analysis and would like to cite your paper.

**Comment by jielisaji** [comment]
Hi Anita, I took a look at your GlasserToColeAnticevicMapping.txt. Did you perform a sorting of the indices in your "CAB Network" column before appending them to the Parcel column? If you open cortex_parcel_network_assignments.mat, it should tell you the network that each Glasser parcel belongs to, in the original left 180, then right 180 parcel order (following the Parcel Index column in the table on Pg 81 of the supplement file you linked). For example, the first 5 values in cortex_parcel_network_assignments.mat values are:
1
2
2
2
2

Indicating that the 1st Glasser parcel (V1 in Pg 81 of the Glasser supplement you cited) belongs to Network 1 (Visual1), and the next four parcels (MST, V6, V2, V3) belong to Network 2 (Visual2). Similarly, indices 181-185 of cortex_parcel_network_assignments.mat are:
1
2
2
2
2
Because these parcels in the right hemisphere are assigned to the same networks.

If you simply append the vector in cortex_parcel_network_assignments.mat to a vector 1-360 you should have the corresponding parcel/network pairing. I hope this addresses your question!

**Comment by amsinha9** [comment]
I think I may have figured out where the confusion stemmed from. Under "Included Files", I interpreted cortex_community_order.mat as the order in which we needed to reorder the 360 Glasser parcels in to then use cortex_parcel_network_assignments.mat (i.e. Glasser parcel 1, 7, 8, 9, etc) to match up the reordered parcels to their corresponding Cole-Anticevic networks (i.e. 1, 2, 2, etc.) . Is cortex_community_order.mat not used for Glasser parcel -> Cole-Anticevic network pairing then?

Just to clarify, if we keep the 360 Glasser parcels in their original order (all 180 left regions first, then 180 right regions), we can simply map one-to-one with the indices in cortex_parcel_network_assignments.mat, correct?

**Comment by jielisaji** [comment]
Ordering by cortex_community_order.mat sorts the 360 parcels in "network order" (i.e. all VIS1 parcels, then VIS2, then SMM etc.). I apologize if this wasn't clear -- I'll update the description of the file in README to hopefully clarify this. The cortical parcels in CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR.dlabel.nii is by default in Glasser parcel order, so you are correct, they match 1-1 with the indices in cortex_parcel_network_assignments.mat.

**Comment by amsinha9** [comment]
Thank you for the clarification, I appreciate it. Makes sense now.
