### ISSUE TITLE
Network mismatch in cortex_parcel_network_assignments.mat

### ISSUE THREAD

**Issue by amsinha9** [ColeLab/ColeAnticevicNetPartition#12]
In a previous issue, it was mentioned that the order in cortex_parcel_network_assignments.mat corresponded to the parcel order in Glasser parcellation, in which all the left parcels correspond to the first 180 indices and the right parcels correspond to the last 180 indices. Given that left and right parcels should belong to the same one out of 12 networks, there is a mismatch in networks assigned to a given left parcel and its corresponding right parcel in cortex_parcel_network_assignments.mat.

After loading cortex_parcel_network_assignments.mat into Matlab, I ran this command: 
mismatch = []; mismatch(:, 1) = netassignments(1:180, 1); mismatch(:, 2) = netassignments(181:360, 1)

See attached mismatch.txt file, in which the first column corresponds to the 180 left parcels' network IDs and the second column corresponds to the 180 right parcels' network IDs .
[mismatch.txt](https://github.com/ColeLab/ColeAnticevicNetPartition/files/4821061/mismatch.txt)

For example, row 11 col. 1 corresponds to L_Premotor Eye Field and row 11 col. 2 corresponds to R_Premotor Eye Field, however, their network ID #s do not match (the left parcel was assigned to 5 (dorsal-attention) , whereas the right parcel was assigned to 4 (Cingulo-opercular)).

These inconsistencies in network IDs are also in rows 25, 28, 58, 62, 74, 81, 82, 93, 104, 128, 162, and 177.

Could you clarify this?

**Comment by jielisaji** [comment]
Hi Anita, the network assignments of the Left 180 and Right 180 parcels are not identical, though they are for the most part the same for analogous L/R parcels. For example, more parcels in the left hemisphere belong to the Language network (e.g. 25, 28), which is consistent with prior literature on left-lateralization of language functions in the brain. We did not force the community detection algorithm to produce a symmetrical solution because there are such known lateralized functions in human brain, hence the "mismatches" that you pointed out.

**Comment by amsinha9** [comment]
That's helpful, thanks for the clarification! Just wanted to make sure I was doing the one-to-one mapping correctly, I appreciate the help!
