### ISSUE TITLE
Using Cole Atlas parcels for extracting BOLD signal

### ISSUE THREAD

**Issue by shilpitju** [ColeLab/ColeAnticevicNetPartition#14]
Hi,

- I have pre-processed my fMRI task data with fMRIPrep and obtained the output dtseries in cifti (fsLR) space. 

1. I visualised output dtseries in wb_view and it seems to be registered with the CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR.dlabel.nii 

However, is there a way so that I know that my time series data is properly registered with the atlas and the signal extracted using the below code actually gives the values for corresponding parcels of the brain.

- Thereafter, I used the LoadParcellatedDataMAtlab_Example.m to parcellate my dtseries and obtain BOLD signal from the language network parcels.

2. The 120X36 matrix (120 dynamics and 36 language parcels (I have omitted one)) generated shows a high level of coherence between the BOLD signals from all the 36 parcels for the entire time series even for a task data. Is it expected or is an error?

Thanks and regards,

Shilpi Modi
![LanguageParcels](https://user-images.githubusercontent.com/57184150/94768973-ebb1e900-037e-11eb-9817-22ba65faf710.jpg)
![tseriesMatSubj](https://user-images.githubusercontent.com/57184150/94768975-ebb1e900-037e-11eb-865b-3492e2f3d59a.jpg)

**Comment by shilpitju** [comment]
Figure 1 is the plot of 120X36 matrix corresponding to the BOLD signal from 36 language parcels. 
Figure 2 is the plot of tseriesMatSubj matrix.

**Comment by jielisaji** [comment]
Hi Shilpi, it is possible for there to be high intra-network correlation with task data (though it may depend to some degree on your data). See Mike's paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4082806/ where they show high correspondence between multi-task networks and resting-state networks.
That being said I do think the subcortex generally tends to have lower GM signal than the cortex, which doesn't look like the case in your Figure 1 (though maybe you have very strong cerebellar signal in your data?). If you are comfortable sharing one of your preprocessed CIFTI data files I'd be happy to take a look at it by Monday. Let me know and I can send you a secure upload link!

**Comment by shilpitju** [comment]
Hi,

Thanks so much. Plz send me the link to upload the data file.

**Comment by jielisaji** [comment]
https://files.yale.edu/upload_request?requestId=ffab40758e970a2c1e3087c80e0a533a

**Comment by shilpitju** [comment]
Files uploaded using the above link.

One cifti file corresponding to rest data
One cifti file corresponding to task data
one cifti file that had few zeros when BOLD was extracted using parcels of the Cole-Antocevic atlas

Please have a look.

Thanks

**Comment by jielisaji** [comment]
Hi Shilpi, it looks like only one datafile (sub-control11_ses-1_task-rest_acq-TR2500_space-fsLR_den-91k_bold.dtseries.nii) and the associated JSON were uploaded? I am not able to replicate the figures you posted above with this file (for one, it has 192 time-points, see the plot of 192 timepoints x 37 Language parcels demeaned BOLD below), so I assume it is not the one shown above.
![image](https://user-images.githubusercontent.com/32307000/95100279-f235bd00-06fe-11eb-8663-bb3bbd460b45.png)


Please try reuploading the files at [this link](https://files.yale.edu/upload_request?requestId=d3ad973d69f314572f7764abe18ec333). This should allow multiple file uploads. The password is "shilpi".

**Comment by shilpitju** [comment]
Hi,

Yes you are right. Actually denoising was creating an error when task effect and its temporal derivative, linear trend in the data and motion spike regressors and their temporal derivatives were taken. 

So now my task data looks pretty normal. However, I am attaching one of the task fmri fmriprep preprocessed file so that whether it is properly registered with Cole-Anticevic atlas can be checked.

Also, few of the data files had few zeros in few columns when BOLD was extracted using parcels of the Cole-Antocevic atlas. Attaching one of such file as well.

Thank you so much for your help.

Regards

**Comment by jielisaji** [comment]
Hi Shilpi, I'm sorry the week got away from me! Glad to hear the error was identified. I'll take a look at the new files tomorrow.

**Comment by shilpitju** [comment]
Thank you very much. Can you also suggest me a way to perform nuissance regression on cifti files to regress out motion and other covariates.

**Comment by jielisaji** [comment]
Hi Shilpi, for nuisance regression/motion scrubbing etc. of CIFTI files we use Qu|Nex, which we have developed and are distributing as a container here: https://qunex.yale.edu/download You can also find links to documentation/user guides on that site.

**Comment by jielisaji** [comment]
Hi Shilpi, the file that has zeros looks like it was cut off in the inferior subcortex (see below), so the zeros are due to missing data. You may want to check if your data are aligned properly to the CIFTI space in intermediate fmriprep steps, or if perhaps the original acquisition didn't cover all of the subcortex. 
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/32307000/95614085-f8e06f00-0a33-11eb-84bf-85f9846acc34.png">

As for the other file, it looks like all of CIFTI space is covered (except for the green strip along the medial wall. I'm not very familiar with fmriprep, but possibly it uses a different medial wall mask than HCP. If this is the case you can still use the Cole-Anticevic parcellation, but these few parcels may not give you much information). 
![image](https://user-images.githubusercontent.com/32307000/95616246-7fe31680-0a37-11eb-8773-acd300d002a3.png)

It also looks like you might have some signal dropout near the edge of the cerebellum. Again, you can still use the parcellation since your data are in the same CIFTI space, but just an FYI that these outer parcels may not hold much data.
![image](https://user-images.githubusercontent.com/32307000/95619211-3cd77200-0a3c-11eb-8132-5bdbdf871d74.png)

**Comment by shilpitju** [comment]
Thank you so much. That was a great help indeed.

I will look into the Qu|Nex program and will seek your help if required.

A quick question, does the dtseries file size get reduced on nuissance regression?

Thanks again.

**Comment by jielisaji** [comment]
Hi Shilpi, the file should not get much smaller after nuisance regression.
I'd be happy to help if you have any questions about Qu|Nex, but I would kindly ask you to sign up and post them at the forum at https://forum.qunex.yale.edu/ since that is really outside the scope of the Cole-Anticevic parcellation. :) Thank you!

**Comment by shilpitju** [comment]
Alright.

Thanks so much.


Shilpi Modi, PhD

Postdoctoral Researcher,

Clinical Brain Mapping and Cognitive Neuroscience Laboratory,

Department of Neurology,

Thomas Jefferson University Sidney Kimmel Medical College,

1025 Walnut Street, Rm. 518,

Philadelphia, PA - 19107

(215) 503-8223
________________________________
