### ISSUE TITLE
Discrepancy in subcortical labels for '*_parcels_LR.dlabel' file and 'data/*parcels_LR.dscalar file'

### ISSUE THREAD

**Issue by RaviMill** [ColeLab/ColeAnticevicNetPartition#22]
Hi, this a somewhat minor issue but the subcortical region labels are different for the 'CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR.dlabel.nii' file and the 'data/CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR.dscalar.nii.file', even though the documentation implies they should be the same. I think the numbering in the dscalar file is more sensible (it goes from 361-718, whereas dlabel goes from 1010-12170), so maybe the dlabel file should be switched to that scheme?

**Comment by jielisaji** [comment]
Hi Ravi, thanks for your query! The subcortical parcels in the dlabel file are primarily labelled rather than numbered, so those numbers that you see (i.e. 1010-12170) are key-values for the purpose of mapping labels to each parcel. We provide the mapping between key-values and the index numbers (i.e. 361-718) [here.](https://github.com/ColeLab/ColeAnticevicNetPartition/blob/master/CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR_LabelKey.txt)

For context, because the subcortical parcels were derived from the cortically-defined networks, the keyvalues actually reflect to the network to which each parcel belongs (e.g. 1010 is the 1st parcel of the 1st network, 1190 is the 19th parcel of the 1st network, 12170 is the 17th parcel of the 12th network) etc.
