### ISSUE TITLE
How to get the parcel name of FCMat_sorted?

### ISSUE THREAD

**Issue by Weihankk** [ColeLab/ColeAnticevicNetPartition#23]
Hi all, 

I have obtain the FCMat_sorted (718*718) by **LoadParcellatedDataInPython_Example.py**  scripts. In the script, the FCMat was ordered by **cortex_subcortex_community_order.txt**. I notice there is another file **CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR_LabelKey.txt**  that store the parcel informations. I'm not sure the first row in FCMat_sorted (first parcel in FCMat_sorted) corresponds to 1 of column NETWORKSORTEDORDER or 1 of  column INDEX in *LabelKey.txt file. 

Maybe my description is a little confusing, in other words, the value in **cortex_subcortex_community_order.txt** correspond to which column in *LabelKey.txt file? The NETWORKSORTEDORDER or INDEX?

Sorry I am a beginner in fMRI, the description may not be clear, if you have any questions, please reply and I will add it in time.

Weihan

**Comment by jielisaji** [comment]
Hi Weihan, 
If you sort the parcels in **CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR.dlabel.nii** by the order provided in **cortex_subcortex_community_order.txt**, the new "index" of the sorted parcel is given in the NETWORKSORTEDORDER column of **CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR_LabelKey.txt**.

The values in **cortex_subcortex_community_order.txt** correspond to the INDEX column in **CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR_LabelKey.txt**.

So for example, parcel with INDEX 121 (`Visual1-05_L-Ctx`) has a NETWORKSORTEDORDER of 2, because it becomes parcel 2 after ordering by the list in **cortex_subcortex_community_order.txt**. Similarly in **cortex_subcortex_community_order.txt**, the first two values are 1 and 121, indicating that parcel with INDEX 1 from **CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR_LabelKey.txt** is still the first parcel after sorting, whereas parcel with INDEX 121 becomes the second parcel after sorting.

I hope that helps!

**Comment by Weihankk** [comment]
Hi jielisaji,
Thank you for your reply. Yes, I sorted the **CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR_LabelKey.txt** by NETWORKSORTEDORDER column, then the INDEX column is same as **cortex_subcortex_community_order.txt**. 

Thanks for your help！

Weihan
