### ISSUE TITLE
wb_command cifti-parcellate throws error: data file is missing voxel (49, 66, 28), which is used by label 'Orbito-Affective'

### ISSUE THREAD

**Issue by LinnBonaventure** [ColeLab/ColeAnticevicNetPartition#24]
Hello, 

I am attempting to parcellate MyelinMap.32k_fs_LR.dscalar.nii files based on your ColeAnticevic atlas using the following code: ${CARET7DIR}/wb_command -cifti-parcellate subjid.MyelinMap.32k_fs_LR.dscalar.nii /path_to_my_HCP_templates/CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_netassignments_LR.dlabel.nii COLUMN subjid.testing.pscalar.nii -method MEAN

I get the following error: "data file is missing voxel (49, 66, 28), which is used by label 'Orbito-Affective'"

Could this be related to only inputting a surface file and therefore not having any "voxels"?  Is there a purely cortical dscalar file that I might have missed? Also, could you please point me to the corresponding .border file in order to get the correct labels for each region (i.e. using wb_command -border-export-color-table or the like). 
Any help would be greatly appreciated!
Kind regards Linn

**Comment by jielisaji** [comment]
Hi Linn! Yes I believe that error is occurring because the myelin files do not have a volume (subcortical) component whereas the dlabel file does. I think you can use `wb_command -cifti-create-label` to make a cortex-only version of the label file and then apply that version to your myelin maps, e.g.:

```
wb_command -cifti-create-label \
Cortex_ColeAnticevic_NetPartition_wSubcorGSR_netassignments_LR.dlabel.nii \
-left-label SeparateHemispheres/CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_netassignments_L.label.gii \
-right-label SeparateHemispheres/CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_netassignments_R.label.gii
```

As for the color/label table, is [this file](https://github.com/ColeLab/ColeAnticevicNetPartition/blob/master/network_labelfile.txt) what you are looking for?

Yours,
Lisa

**Comment by LinnBonaventure** [comment]
Great, thanks so much for the quick and very helpful reply!

Kind regards Linn
